FROM node:22-alpine

WORKDIR /app

COPY package.json package-lock.json vite.config.ts tsconfig.json ./

RUN npm install --include=dev

COPY . .

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "5173"]