# Build the frontend
FROM node:20 AS build

WORKDIR /app

COPY package*.json ./

ENV VITE_API_URL=https://optimaprime.be/
ENV VITE_API_TIMEOUT=10000

RUN npm ci

COPY . .

RUN npm run build

# Serve with Nginx
FROM nginx:alpine

COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf

WORKDIR /usr/share/nginx/html

RUN rm -rf ./*

COPY --from=build /app/public /usr/share/nginx/html

CMD ["nginx", "-g", "daemon off;"]
