apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-certificate
  namespace: default
spec:
  secretName: ingress-certs
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: optimaprime.designproject.idlab.ugent.be
