"""Rename organization models to model ids

Revision ID: 1b444a346180
Revises: d7c770d015a1
Create Date: 2025-05-18 16:09:36.634719

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1b444a346180"
down_revision: Union[str, None] = "d7c770d015a1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "organizations",
        sa.Column("model_ids", sa.JSON(), nullable=False, server_default="[]"),
    )
    op.drop_column("organizations", "models")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "organizations",
        sa.Column(
            "models",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("organizations", "model_ids")
    # ### end Alembic commands ###
