"""added email to invite

Revision ID: 81b2800397d3
Revises: 5bd4f34f0c2e
Create Date: 2025-05-16 20:37:57.775223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81b2800397d3'
down_revision: Union[str, None] = '5bd4f34f0c2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invites', sa.Column('email', sa.String(), nullable=False))
    op.drop_constraint('invites_user_id_fkey', 'invites', type_='foreignkey')
    op.drop_column('invites', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invites', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('invites_user_id_fkey', 'invites', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('invites', 'email')
    # ### end Alembic commands ###
