"""Job execution attempts and original file name

Revision ID: a6b59a888a1b
Revises: 663c8cc84c5e
Create Date: 2025-05-17 11:18:24.557441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6b59a888a1b'
down_revision: Union[str, None] = '5bd4f34f0c2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mapping_job_executions', sa.Column('attempts', sa.Integer(), server_default='0', nullable=False))
    op.add_column('mapping_job_executions', sa.Column('original_file_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mapping_job_executions', 'original_file_name')
    op.drop_column('mapping_job_executions', 'attempts')
    # ### end Alembic commands ###
