"""dynamic mapping jobs

Revision ID: b964393f484f
Revises: 95524bf3effd
Create Date: 2025-05-19 21:39:43.454484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b964393f484f'
down_revision: Union[str, None] = '95524bf3effd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mapping_job_executions', sa.Column('json_data', sa.JSON(), nullable=True))
    op.alter_column('mapping_job_executions', 'input_file_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('mapping_jobs', sa.Column('uuid', sa.String(), nullable=True))
    op.add_column('mapping_jobs', sa.Column('external_api_endpoint', sa.String(), nullable=True))
    op.create_index('ix_mapping_jobs_uuid', 'mapping_jobs', ['uuid'], unique=False)
    op.create_unique_constraint(None, 'mapping_jobs', ['uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mapping_jobs', type_='unique')
    op.drop_index('ix_mapping_jobs_uuid', table_name='mapping_jobs')
    op.drop_column('mapping_jobs', 'external_api_endpoint')
    op.drop_column('mapping_jobs', 'uuid')
    op.alter_column('mapping_job_executions', 'input_file_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('mapping_job_executions', 'json_data')
    # ### end Alembic commands ###
