"""Cascade delete on jobs, added target path on mappings

Revision ID: bead192ecc5e
Revises: 4ca668be2fb5
Create Date: 2025-05-15 23:24:32.884419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bead192ecc5e'
down_revision: Union[str, None] = '4ca668be2fb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('mapping_job_executions_source_mapping_id_fkey', 'mapping_job_executions', type_='foreignkey')
    op.drop_constraint('mapping_job_executions_mapping_job_id_fkey', 'mapping_job_executions', type_='foreignkey')
    op.create_foreign_key(None, 'mapping_job_executions', 'mapping_jobs', ['mapping_job_id'], ['id'], ondelete='cascade')
    op.create_foreign_key(None, 'mapping_job_executions', 'source_mappings', ['source_mapping_id'], ['id'], ondelete='cascade')
    op.drop_constraint('mapping_jobs_organization_id_fkey', 'mapping_jobs', type_='foreignkey')
    op.drop_constraint('mapping_jobs_user_id_fkey', 'mapping_jobs', type_='foreignkey')
    op.drop_constraint('mapping_jobs_input_definition_id_fkey', 'mapping_jobs', type_='foreignkey')
    op.create_foreign_key(None, 'mapping_jobs', 'input_definitions', ['input_definition_id'], ['id'], ondelete='cascade')
    op.create_foreign_key(None, 'mapping_jobs', 'users', ['user_id'], ['id'], ondelete='cascade')
    op.create_foreign_key(None, 'mapping_jobs', 'organizations', ['organization_id'], ['id'], ondelete='cascade')
    op.add_column('source_mappings', sa.Column('target_path', sa.String(), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('source_mappings', 'target_path')
    op.drop_constraint(None, 'mapping_jobs', type_='foreignkey')
    op.drop_constraint(None, 'mapping_jobs', type_='foreignkey')
    op.drop_constraint(None, 'mapping_jobs', type_='foreignkey')
    op.create_foreign_key('mapping_jobs_input_definition_id_fkey', 'mapping_jobs', 'input_definitions', ['input_definition_id'], ['id'])
    op.create_foreign_key('mapping_jobs_user_id_fkey', 'mapping_jobs', 'users', ['user_id'], ['id'])
    op.create_foreign_key('mapping_jobs_organization_id_fkey', 'mapping_jobs', 'organizations', ['organization_id'], ['id'])
    op.drop_constraint(None, 'mapping_job_executions', type_='foreignkey')
    op.drop_constraint(None, 'mapping_job_executions', type_='foreignkey')
    op.create_foreign_key('mapping_job_executions_mapping_job_id_fkey', 'mapping_job_executions', 'mapping_jobs', ['mapping_job_id'], ['id'])
    op.create_foreign_key('mapping_job_executions_source_mapping_id_fkey', 'mapping_job_executions', 'source_mappings', ['source_mapping_id'], ['id'])
    # ### end Alembic commands ###
