"""Organization branch field

Revision ID: d7c770d015a1
Revises: 2cdb1b949271
Create Date: 2025-05-17 22:27:53.202851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7c770d015a1'
down_revision: Union[str, None] = '2cdb1b949271'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('branch', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'branch')
    # ### end Alembic commands ###
