apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry-ui
  template:
    metadata:
      labels:
        app: registry-ui
    spec:
      containers:
        - name: registry-ui
          image: joxit/docker-registry-ui:latest
          ports:
            - containerPort: 80
          env:
            - name: REGISTRY_TITLE
              value: "My Private Registry"
            - name: NGINX_PROXY_PASS_URL
              value: "http://local-registry:5000"
            - name: SINGLE_REGISTRY
              value: "true"
          volumeMounts:
            - name: auth
              mountPath: /auth
              readOnly: true
      volumes:
        - name: auth
          hostPath:
            path: /etc/registry
            type: Directory
