apiVersion: v1
kind: Service
metadata:
  name: local-registry
spec:
  selector:
    app: local-registry
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30069
  type: NodePort
